MONITOR_INTERVAL_SECONDS: 10.0

PATHS:
  STATE_DIR: "./logs/state"
  LOG_DIR: "./logs"


DEVICE_ID_POLICY:
  SERIES: 1
  WIDTH: 3
  RADIX: device36
  UPPERCASE: true
  PREFIX: ""

SUBSCRIBERS:
  MONITOR: true
  TIME_CONTROL: true
  CONSTRAINT: true
  ALERT: true
  ALERT_NOTIFIERS: true
  CONTROL: true
  DATA_SENDER: true
