MONITOR_INTERVAL_SECONDS: 10.0
MONITOR_READ_CONCURRENCY: 50
MONITOR_DEVICE_TIMEOUT_SEC: 3.0
MONITOR_LOG_EACH_DEVICE: false

PATHS:
  STATE_DIR: "./logs/state"
  LOG_DIR: "./logs"

REMOTE_ACCESS:
  REVERSE_SSH:
    PORT_SOURCE: "config"   # config | mqtt
    PORT: 22              # only used when PORT_SOURCE=config, default 22

DEVICE_ID_POLICY:
  SERIES: 1
  WIDTH: 3
  RADIX: device36
  UPPERCASE: true
  PREFIX: ""

SUBSCRIBERS:
  MONITOR: true
  TIME_CONTROL: true
  CONSTRAINT: true
  ALERT: true
  ALERT_NOTIFIERS: true
  CONTROL: true
  DATA_SENDER: true
  INITIALIZATION: true
  SNAPSHOT_SAVER: true